### ISSUE TITLE
Contribute !

### ISSUE THREAD

**Issue by qu35t-code** [Hazegard/htb-prolab-cli#1]
Hi, the best if you base on *my code*, is to make a **PR** on the original repo to contribute !
https://github.com/GoToolSharing/htb-cli/pulls

**Comment by Hazegard** [comment]
Hello!

Actually, I reused your API function but I didn't bother trying to reuse your cli function, so I implemented a custom output which is totally different from yours.
That's why I didn't try to contribute.

But if I can find the time to do so, I'll give it a try.

**Comment by qu35t-code** [comment]
No worries, just think that if you reuse my code, because of the license, you have to put the same license as mine. I'll let you read it ;) gl
